<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.talend.studio</groupId>
		<artifactId>tesb-studio-se</artifactId>
		<version>8.9.0-SNAPSHOT</version>
		<relativePath>../../../</relativePath>
	</parent>
	<artifactId>org.talend.rcp.branding.esbstandard</artifactId>
	<packaging>eclipse-plugin</packaging>
	
	<properties>
		<!-- Used by filtered files and then imported by product module with properties-maven-plugin -->
		<launcher.prefix>TOS_ESB</launcher.prefix>
		<storage.prefix>${launcher.prefix}</storage.prefix>
		<storage.dir>esb</storage.dir>
		<product.name>Talaxie Open Studio for ESB</product.name>
		<product.branding.platform>${project.artifactId}</product.branding.platform>
		<product.branding.id>${project.artifactId}.product</product.branding.id>
		<mac.launcher.info>${product.name} for Mac OS X, Copyright Talaxie. 2006-2015. All rights reserved.</mac.launcher.info>
		<product.website>http://www.deilink.fr\n</product.website>
	</properties>

	<build>
		<resources>
			<resource>
				<directory>filtered-resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<executions>
					<execution>
						<id>default-deploy</id>
						<phase>deploy</phase>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>attach-license-artifact</id>
						<phase>package</phase>
						<goals>
							<goal>attach-artifact</goal>
						</goals>
						<configuration>
							<artifacts>
								<artifact>
									<file>./resources/license.txt</file>
									<type>txt</type>
									<classifier>license</classifier>
								</artifact>
								<artifact>
									<file>./resources/NOTICE.txt</file>
									<type>txt</type>
									<classifier>notice</classifier>
								</artifact>
								<artifact>
									<file>${project.build.outputDirectory}/.eclipseproduct</file>
									<type>txt</type>
									<classifier>eclipseproduct</classifier>
								</artifact>
							</artifacts>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
